print("Installing GimpOCD")
print("Creating Directories")
os.execute("mkdir /home/GimpOCD")
os.execute("mkdir /home/GimpOCD/modules")
os.execute("mkdir /home/GimpOCD/lib")
os.execute("mkdir /usr/bin")

print("Removing Any Previous Versions")
os.execute("rm -rf /home/GimpOCD/modules/*")
os.execute("rm -rf /home/GimpOCD/lib/*")
os.execute("rm -f /usr/bin/GimpOCD.lua")

print("Downloading Files")
os.execute("wget -f https://raw.githubusercontent.com/Gimpeh/GimpOCD-Divergence/refs/heads/main/GimpOCD.lua /usr/bin/GimpOCD.lua")
os.execute("wget -f https://raw.githubusercontent.com/Gimpeh/GimpOCD-Divergence/refs/heads/main/lib/configurableWindows.lua /home/GimpOCD/lib/configurableWindows.lua")
os.execute("wget -f https://raw.githubusercontent.com/Gimpeh/GimpOCD-Divergence/refs/heads/main/lib/gimpColors.lua /home/GimpOCD/lib/gimpColors.lua")
os.execute("wget -f https://raw.githubusercontent.com/Gimpeh/GimpOCD-Divergence/refs/heads/main/lib/gimpHelper.lua /home/GimpOCD/lib/gimpHelper.lua")
os.execute("wget -f https://raw.githubusercontent.com/Gimpeh/GimpOCD-Divergence/refs/heads/main/lib/widgetsAreUs.lua /home/GimpOCD/lib/widgetsAreUs.lua")
os.execute("wget -f https://raw.githubusercontent.com/Gimpeh/GimpOCD-Divergence/refs/heads/main/modules/powerDisplay.lua /home/GimpOCD/modules/powerDisplay.lua")

print("Installation complete!")
print("run GimpOCD from the command line to start")
print("If accelerating, include the acceleration multiplier as an arg (e.g. GimpOCD 128)")
os.execute("rm setup.lua")